version: "3.4"

services:
  octobercms:
    build: .
    image: dynamedia/docker-octobercms:v1.0.446
    env_file:
      - .env
    restart: unless-stopped
    # October CMS needs to maintain state so it's a good idea to mount some volumes
    volumes:
      - ./data/storage:/var/www/app/storage/app/
      - ./data/plugins:/var/www/app/plugins/
      - ./data/themes:/var/www/app/themes/
      # - ./.env-append:/var/www/app/.env-append
    # In production you'll want to have https. Use a reverse proxy ssl terminator in front of this container
    #ports:
    #  - 80:80
    expose:
      - 80
